DROP DATABASE IF EXISTS DB_VACINACAO;
CREATE DATABASE DB_VACINACAO;
USE DB_VACINACAO;

CREATE TABLE PESQUISADOR (
	IDPESQUISADOR INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100),
    DATA_NASCIMENTO DATE,
    SEXO ENUM('MASCULINO', 'FEMININO'),
    CPF VARCHAR(11),
    REACAO INT(5),
    INSTITUICAO VARCHAR(100),
    PRIMARY KEY (IDPESQUISADOR)
);

CREATE TABLE PACIENTE (
	IDPACIENTE INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100),
    DATA_NASCIMENTO DATE,
    SEXO ENUM('MASCULINO', 'FEMININO'),
    CPF VARCHAR(11),
    REACAO INT(5),
    VOLUNTARIO BOOLEAN,
    PRIMARY KEY (IDPACIENTE)
);

CREATE TABLE VACINA (
	IDVACINA INT NOT NULL AUTO_INCREMENT,
    PESQUISADOR VARCHAR(45) NOT NULL,
    PAIS VARCHAR(45),
    ESTAGIO ENUM('INICIAL', 'TESTES', 'APLICAÇÃO EM MASSA'),
    DT_INICIO_PESQUISA DATE,
	PRIMARY KEY (IDVACINA),
    FOREIGN KEY (IDPESQUISADOR) REFERENCES PESQUISADOR (IDPESQUISADOR)
);

select * from pesquisador;
select * from vacina;
select * from paciente;